// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/yarincep/database-go-demo/database/users/model"
)

// UserServiceRepository is an autogenerated mock type for the UserServiceRepository type
type UserServiceRepository struct {
	mock.Mock
}

// GetUserByID provides a mock function with given fields: userID
func (_m *UserServiceRepository) GetUserByID(userID int) (*model.User, error) {
	ret := _m.Called(userID)

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*model.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int) *model.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserServiceRepository creates a new instance of UserServiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceRepository {
	mock := &UserServiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
